.travis.yml, build.gradle.kts, server/gradle/docker.gradle.kts, server/src/endtoend-test/kotlin/com/delphix/titan/DockerUtil.kt, server/src/scripts-test/test-util.sh, server/src/scripts/util.sh
This adds support for publishing artifacts via the Travis job:
- titan-client library for use by the CLI (as GitHub release)
- titandata/titan docker image
This requires configuring the job with dockerhub and github credentials. We can explore GitHub packages when they become generally available to see if we can simplify this.
Ran many jobs on my fork of the repo.
=> Publish artifacts through Travis

.travis.yml
There was a typo in the travis configuration that wasn't setting the `titanVersion` variable properly when publishing the client.
=> Fix titan version when publishing client

client/build.gradle.kts, server/build.gradle.kts, server/src/endtoend-test/kotlin/io/titandata/S3WorkflowTest.kt
The previous changes had the group ID as "io.titan-data", which is invalid. This changes it to "io.titandata". Derek has also been hitting some issues with S3 and multiple commits, so this push adds an end2end test for that.
Derek tested ability to pull in published pom files. I ran the S3Workflow end2end tests.
=> Update group ID

server/src/integration-test/kotlin/io/titandata/RemotesApiTest.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsOperationManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsRepositoryManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsOperationTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsRepositoryTest.kt
Fixes #10 
The only place we have sensitive information is in remote configuration, and the only place those are logged is when we run "zfs set". This change creates a wrapper method to safely set properties by obscuring the values. I considered more complex changes that would involve different JSON serialization contexts, etc, but decided it was overkill for what we need right now.
`gradle build endtoendTest`
Also looked at the logs during the end to end tests and made sure we were obscuring values, such as:
```
2019-09-23 23:09:09.731 [DefaultDispatcher-worker-5] ERROR io.titandata.util.CommandExecutor - Exit 1: zfs set io.titan-data:remotes=***** test/repo/foo
```
=> titan-server should not log sensitive information

.github/workflows/push.yml, .github/workflows/release.yml, server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt
Fixes #14 
This adds some code to capture docker errors while running end to end tests. It also updates the actions to run endtoend tests on push and release. For now, we only are running the LocalWorkflowTest (hence not closing #13) as I'll need to do some community AWS work to set up a S3 bucket for the S3 tests. The docker logs aren't perfect - we don't get a splicing of both stdout and stderr together, but it's enough to make forward progress.
Ran new actions on my fork, verified that end to end tests worked.
=> End to end tests should capture docker logs

.github/workflows/release.yml
Github private docker package registry is giving "unknown blob" errors, even though it worked when pushing to 'eschrock/titan-server'. Rather than debug this whole thing now, let's switch back to dockerhub and keep using the image path we were using before.
=> switch to dockerhub

server/src/main/kotlin/io/titandata/remote/ssh/SshRemoteProvider.kt, server/src/main/kotlin/io/titandata/sync/RsyncExecutor.kt, server/src/test/kotlin/io/titandata/remote/ssh/SshRemoteProviderTest.kt
Fixes #39 
Added option to ssh command build to redirect writing known hosts to /dev/null. This is accepted best practice to avoid writing host keys to the user's ~/.ssh/config file
tested locally on my fork
=> disabling writing known_hosts

client/src/main/kotlin/io/titandata/models/S3Parameters.kt, client/src/main/kotlin/io/titandata/serialization/remote/S3RemoteUtil.kt, server/src/main/kotlin/io/titandata/remote/s3/S3RemoteProvider.kt, server/src/test/kotlin/io/titandata/serialization/S3RemoteTest.kt, server/src/test/kotlin/io/titandata/serialization/SshRemoteTest.kt
Fixes #30 
This fix will fetch the session token from the client and pass that to the server. Why you have to check the instance type of the object returned I don't know, but that's apparently the interface.
After getting credentials from `aws sts get-session-token` and setting environment variables, with current titan:
```
$ titan clone s3://titan-data-demo/hello-world/postgres hello-world
Clone failed.
The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: AE9AE0C236B7E357; S3 Extended Request ID: uKxN8c7SyScgymGk4i3BhzY9LMRcxCNJb4UFn9UeX3BVgRrCVXXGxNzd+vSXr0zwMAF7uXwFPyc=)
hello-world removed
```
With fix in place:
```
$ java -jar ./target/titan-0.3.1-jar-with-dependencies.jar clone …
```
=> S3 provider doesn't work with MFA credentials

.github/workflows/push.yml, .github/workflows/release.yml, server/build.gradle.kts
Fixes #13 
This adds support for running all of our endtoend tests, including the S3 and SSH tests. It relies on the new S3 test bucket that was added to the community infrastructure. Ideally, I shouldn't have to specifically include tests, they should just be skipped if the config isn't present. But kotlintest SkipTestException is not working as I'd expect (bug filed), so for now I explicitly call out the ones I want. This way we skip running the engine endtoend tests.
Ran on my fork.
=> endtoend tests for S3 and SSH

.github/workflows/release.yml, client/build.gradle.kts
Turns out that accessing the github package registry maven repository requires github credentials, which makes using anything within it quiet annoying. This switches us back to publishing to S3 until public read access is enabled for the github package registry.
Pushed a tag to my fork and observed the artifacts built & published.
=> publish maven artifacts to S3

server/src/scripts/zfs.sh
Fixes #42 
This fix turns on lz4 compression for all repositories. While we could add the capbility to turn this on for existing installations, given the current number of users it seems overkill to add that level of complexity. So this will only affect new installations.
Build & end to end tests. Verified that compression is set:
```
zfs list -o name,compression
NAME            COMPRESS
titan                off
titan/deathrow       off
titan/repo           lz4
```
=> turn on compression

client/src/main/kotlin/io/titandata/client/apis/CommitsApi.kt, client/src/main/kotlin/io/titandata/models/CommitStatus.kt, server/src/endtoend-test/kotlin/io/titandata/LocalWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/main/kotlin/io/titandata/apis/CommitsApi.kt, server/src/main/kotlin/io/titandata/storage/StorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsCommitManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsCommitTest.kt
Fixes #26 
This adds a new "/status" endpoint to the commit API that returns a sum of the ZFS sizes for all the descendent snapshots of the commit. I used a separate endpoint because (a) this information is more expensive to calculate and (b) the commit structure is serialized in various forms and shouldn't really container "dynamic" information like sizes. I chose note to include a per-volume breakdown for now until someone tells us it would be useful.
./gradle build endtoendTest
=> provide size information for commits

client/src/main/kotlin/io/titandata/client/apis/RepositoriesApi.kt, client/src/main/kotlin/io/titandata/models/RepositoryStatus.kt, client/src/main/kotlin/io/titandata/models/RepositoryVolumeStatus.kt, server/src/endtoend-test/kotlin/io/titandata/LocalWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/apis/RepositoriesApi.kt, server/src/main/kotlin/io/titandata/storage/StorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsRepositoryManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/test/kotlin/io/titandata/serialization/S3RemoteTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsRepositoryTest.kt
Fixes #21 
This adds a new `repository/<name>/status` endpoint that will return information about the repository that can't be retrieved through other means. This includes the current size information as well as the source of the commit it was cloned from. It also provides a few pieces of information for convenience, like the last commit, to simplify the client.
Unit, integration, and endtoend tests.
=> endpoint for reporting repository status

server/src/scripts-test/test-zfs.sh, server/src/scripts/zfs.sh
Fixes #18 
This started off pretty easily, but in the process I learned that I whiffed on some of the ZFS version checks. I need to use the newest ZFS userland with older kernels, not vice versa. And we don't want to use just any compatible module off of the titan-data volume, otherwise we won't use the latest ZFS version we shipped. So I modified it to make a more exact match.
Build and endtoend test. Verified that ZFS 0.8.2 is running on titan-server. Ran through a variety of different ZFS versions, running on the system, installed on titan-data, etc.
=> update ZFS to 0.8.2

.github/workflows/push.yml, .github/workflows/release.yml, client/build.gradle.kts, client/src/main/kotlin/io/titandata/client/infrastructure/Errors.kt, client/src/main/kotlin/io/titandata/remote/s3web/S3WebParameters.kt, client/src/main/kotlin/io/titandata/remote/s3web/S3WebRemote.kt, client/src/main/kotlin/io/titandata/remote/s3web/S3WebRemoteUtil.kt, client/src/main/kotlin/io/titandata/serialization/ModelTypeAdapters.kt, client/src/main/kotlin/io/titandata/serialization/RemoteUtil.kt, engine/build.gradle.kts, engine/src/main/kotlin/com/delphix/sdk/Http.kt, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat, server/build.gradle.kts, server/gradle/docker.gradle.kts, server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/endtoend-test/kotlin/io/titandata/remote/s3web/S3WebWorkflowTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/remote/s3/S3RemoteProvider.kt, server/src/main/kotlin/io/titandata/remote/s3web/S3WebRemoteProvider.kt, server/src/test/kotlin/io/titandata/remote/s3web/S3WebRemoteTest.kt
Fixes #31 
This creates a read-only HTTP provider that can pull from commits generated by the 's3' provider. While I was here, I also updated some dependencies (leaving OKHTTP for the client since I believe 4.x causes problems).
Build and run all endtoend tests (including new one).
=> add s3web provider

client/src/main/kotlin/io/titandata/models/RepositoryStatus.kt, server/src/endtoend-test/kotlin/io/titandata/LocalWorkflowTest.kt, server/src/endtoend-test/kotlin/io/titandata/remote/s3/S3WorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/remote/s3/S3RemoteProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsCommitManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsRepositoryManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsRepositoryTest.kt
Fixes #54 
While testing the new tags changes, I found that S3 was broken. When we updated the metadata, we did not include a trailing newline in the S3 metadata. When you later pushed another commit, this would end up with two commits on the same line, breaking the ability to list commits from then on.
While I was there, I also fixed #54 so that we track the proper sourceCommit for any repository. The source commit is the "last commit" prior to the current state. This is either (a) the previous commit if one was made after checkout, or (b) the source commit of the checkout if no commits have been made since.
Build, test, integration test, end to end test. Manually tested with in-progress CLI support for tags.
=> Add source commit and fix S3 metadata update

server/docker/sshtest.Dockerfile, server/gradle/docker.gradle.kts, server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt
We now have a `titandata/ssh-test-server` image that we can share across titan projects. This switches `titan-server` over to use it.
Ran SshWorkflow endtoend tests.
=> switch to published sshtest

server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/endtoend-test/kotlin/io/titandata/remote/engine/EngineWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/RemotesApiTest.kt, server/src/main/kotlin/io/titandata/apis/RemotesApi.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/remote/s3/S3RemoteProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsOperationManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsRepositoryManager.kt, server/src/main/kotlin/io/titandata/sync/RsyncExecutor.kt
Fixes #27 
This addresses all remaining TODO comments. They were all fixed, with the exception of two:
- The engine login commit was simply removed because we'll move away from this model in the near future
- The s3 progress monitoring was removed because it's now covered by a GitHub issue
It also turned out that I long ago changed the rules to prohibit volume names starting with "_" but just never deleted the comment.
Build, test, integration test, endtoend test.
=> TODO cleanup

server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/endtoend-test/kotlin/io/titandata/remote/ssh/SshWorkflowTest.kt, server/src/scripts/launch, server/src/scripts/teardown, server/src/scripts/titan.sh, server/src/scripts/zfs.sh
Fixes #19 
This improves the teardown process to handle cases where volumes may still be mounted (as is the case when end2end tests fail unexpectedly). While I was here, I also updated titan-server to run on a dedicated bridge network. This is just generally good practice, but has the advantage that we can then run the ssh test server on that network and not have to rely on finding the local machine's IP, which is flaky.
Build, test, integration test, and end2end tests.
=> improve teardown and network isolation

server/build.gradle.kts, server/docker/server.Dockerfile, server/gradle/ktlint.gradle.kts, server/src/scripts/run, server/src/scripts/titan.sh, server/src/scripts/zfs.sh
This adds the infrastructure work to have a working database within titan-server, and adds some of the dependencies we'll need to use it. As part of making titan-server more scalable, and prepping for k8s support, we're adding a metadata layer on top of the data layer. I opted for postgres over an embedded database (though we'll use H2 for in-memory testing) primarily because it makes it way easier to debug via the psql command line, and provides easier migration paths and future flexibility should we want to run that postgresql database in a different manner (e.g. via RDS). It will potentially give us access to some nice features like jsonb fields, etc.
Build, test, endtoend tests. Ran titan-server and ensured that postgres was running and we could connect to the titan database.
=> configure a database for titan-server

server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RemotesApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/integration-test/kotlin/io/titandata/VolumesApiTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/metadata/MetadataProvider.kt, server/src/main/kotlin/io/titandata/metadata/table/Repositories.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/RepositoryOrchestrator.kt, server/src/main/kotlin/io/titandata/storage/StorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsOperationManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/test/kotlin/io/titandata/metadata/MetadataProviderTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsOperationTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsRepositoryTest.kt
This adds the metadata layer on top of the data layer for repositories, and we now consult the metadata layer for all reads and updates of repositories. However, this is only phase one because we're still leaving the storage layer untouched, creating and destroying repositories there. The next phase will involve getting rid of the concept of repositories at the storage layer but that's a ton more work and requires moving more pieces to be metadata only.
Build, test, integrationTest, endtoendTest.
=> repository metadata, phase one

server/src/endtoend-test/kotlin/io/titandata/LocalWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RemotesApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/metadata/MetadataProvider.kt, server/src/main/kotlin/io/titandata/metadata/table/Remotes.kt, server/src/main/kotlin/io/titandata/orchestrator/NameUtil.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/RemoteOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/RepositoryOrchestrator.kt, server/src/main/kotlin/io/titandata/storage/StorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsRepositoryManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/test/kotlin/io/titandata/metadata/RemoteMetadataTest.kt, server/src/test/kotlin/io/titandata/metadata/RepositoryMetadataTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsRepositoryTest.kt
This moves the remotes from being stored on-disk as part of ZFS to the database layer. While testing this, some of the shenanigans I was doing trying to mock out the metadata layer were causing problems, so I left it intact and instead switched to clearing it before each test.
Build, test, integrationTest, endtoendTest
=> remotes as metadata

server/src/integration-test/kotlin/io/titandata/VolumesApiTest.kt, server/src/main/kotlin/io/titandata/apis/VolumesApi.kt, server/src/main/kotlin/io/titandata/metadata/MetadataProvider.kt, server/src/main/kotlin/io/titandata/metadata/table/Volumes.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/orchestrator/VolumeOrchestrator.kt, server/src/main/kotlin/io/titandata/storage/StorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsOperationManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsRepositoryManager.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsVolumeManager.kt, server/src/test/kotlin/io/titandata/metadata/VolumeMetadataTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/remote/ssh/SshRemoteProviderTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsOperationTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsVolumeTest.kt
This is the next step in moving content into the metadata layer, this time with volumes. As with the other migrations, this has exposed plenty of oddities in the APIs and interactions between the layers. We really should have a generic titan Volume model that is different from the docker API, and volumes are cloned within the storage provider layer but then created after the fact, etc. But until the metadata layer migration is complete, I don't want to muck with the core storage / orchestrator flow. I'll come back and fix up these oddities once the core metadata layer migration is complete.
Gradle build / test / integrationTest, and endtoendTest (minus engine tests).
=> add volumes to metadata layer

server/gradle/docker.gradle.kts
When I switched over to using the published sshtest, I apparently deleted too much of the build file. This restores the missing tasks to publish docker images.
=> restore missing publish tasks

.github/workflows/nightly.yml, README.md
I previously set up the end to end tests to run with every push. This was always likely overkill, and now is probably the time to move to a nightly model. We also add some badges to the README.
=> run endtoend tests nightly

server/src/endtoend-test/kotlin/io/titandata/LocalWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/main/kotlin/io/titandata/orchestrator/CommitOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/Reaper.kt, server/src/main/kotlin/io/titandata/storage/StorageProvider.kt, server/src/main/kotlin/io/titandata/storage/zfs/ZfsStorageProvider.kt, server/src/scripts/zfs.sh, server/src/test/kotlin/io/titandata/orchestrator/CommitOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/storage/zfs/ZfsStorageProviderTest.kt
This addresses a number of recent regression int he 6.0 release:
- We created a dataset for the postgres DB on persistent storage but set the mountpoint incorrectly so it was never properly mounted
- Within the reaper, if we ever end up with metadata but no data (possible in various scenarios), we'd never clean up the metadata. Storage deletion should be idempotent
- When creating or cloning volumes for operations, we failed to update the provider-based ocnfig, resulting in re-using of mountpoints
` gradle build test integrationTest endtoendTest`. Also ran titan binary from mcred, verified that datasets were being properly deleted on the backend.
=> fixes for 0.6.0 regressions

server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/endtoend-test/kotlin/io/titandata/remote/ssh/SshWorkflowTest.kt, server/src/main/kotlin/io/titandata/orchestrator/RemoteOrchestrator.kt, server/src/test/kotlin/io/titandata/orchestrator/RemoteOrchestratorTest.kt
The previous validation fix worked for the calls that take in remotes and remote parameters, but neglected the cases where we were looking them up from the metadata store. This caused tests to fail because we'd deserialize to a double. The fix is to validate on read, even for internal operations.
`gradle build test integrationTest`
=> fix validation for remote operations

DEVELOPING.md, server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/integration-test/kotlin/io/titandata/DockerVolumesApiTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/context/docker/DockerZfsContext.kt, server/src/main/kotlin/io/titandata/metadata/MetadataProvider.kt, server/src/main/kotlin/io/titandata/metadata/OperationData.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/orchestrator/CommitOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/Reaper.kt, server/src/main/kotlin/io/titandata/orchestrator/RepositoryOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/VolumeOrchestrator.kt, server/src/test/kotlin/io/titandata/context/docker/DockerZfsContextTest.kt, server/src/test/kotlin/io/titandata/metadata/OperationMetadataTest.kt, server/src/test/kotlin/io/titandata/metadata/ProgressEntryMetadataTest.kt, server/src/test/kotlin/io/titandata/operation/OperationExecutorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/CommitOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/ReaperTest.kt, server/src/test/kotlin/io/titandata/orchestrator/RemoteOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/RepositoryOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/VolumeOrchestratorTest.kt
This is a large but rename-only PR. In the future, we're going to have to support different ways of running operations. This will be tied to how the storage is managed, so rather than having the notion of a "storage provider", we'll be moving to a more general notion of a "runtime context". This PR just lays the groundwork for the renaming, and contains no logic changes.
`gradle build test integrationTest endtoendTest`
=> rename zfs storage provider

server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/integration-test/kotlin/io/titandata/DockerVolumesApiTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RemotesApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/apis/CommitsApi.kt, server/src/main/kotlin/io/titandata/apis/DockerVolumesApi.kt, server/src/main/kotlin/io/titandata/apis/OperationsApi.kt, server/src/main/kotlin/io/titandata/apis/RemotesApi.kt, server/src/main/kotlin/io/titandata/apis/RepositoriesApi.kt, server/src/main/kotlin/io/titandata/apis/VolumesApi.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/orchestrator/CommitOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/Reaper.kt, server/src/main/kotlin/io/titandata/orchestrator/RemoteOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/RepositoryOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/VolumeOrchestrator.kt, server/src/test/kotlin/io/titandata/operation/OperationExecutorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/CommitOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/ReaperTest.kt, server/src/test/kotlin/io/titandata/orchestrator/RemoteOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/RepositoryOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/VolumeOrchestratorTest.kt
It's been bugging me for a while that we've had this thing called a `ProviderModule` that dates back from the dawn of building the ktor app, but it's really a service locator. We should rename it now, as we're going to be doing some surgery to it to support multiple runtime contexts. There are no logic changes involved.
`gradle build test integrationTest endtoendTest`
=> rename service locator

server/build.gradle.kts, server/src/endtoend-test/kotlin/io/titandata/docker/DockerVolumeApi.kt, server/src/endtoend-test/kotlin/io/titandata/docker/DockerVolumeTest.kt, server/src/endtoend-test/kotlin/io/titandata/docker/LocalWorkflowTest.kt, server/src/endtoend-test/kotlin/io/titandata/docker/TeardownTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesContextTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/context/docker/DockerZfsContext.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesCsiContext.kt, server/src/main/kotlin/io/titandata/orchestrator/CommitOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/Reaper.kt, server/src/scripts/run, server/src/scripts/util.sh, server/src/test/kotlin/io/titandata/context/docker/DockerZfsContextTest.kt, server/src/test/kotlin/io/titandata/operation/OperationExecutorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/CommitOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/ReaperTest.kt, server/src/test/kotlin/io/titandata/orchestrator/RepositoryOrchestratorTest.kt
This adds k8s implementation for create and delete volume. In the process, I rejiggered some of the packages for endtoend tests. Note that there are some big questions about how we manage volume configuration unique to k8s, most notably volume sizes (which don't exist in ZFS), but also things like non-default k8s configurations and storage classes. For now I'm just hard-coding everything (including a 1GiB size for all volumes) through the alpha.
`gradle rebuild test integrationTest endtoeendTest` including k8s endtoend tests.
=> k8s create/delete volumes and commits

client/src/main/kotlin/io/titandata/client/apis/VolumesApi.kt, client/src/main/kotlin/io/titandata/models/CommitStatus.kt, client/src/main/kotlin/io/titandata/models/RepositoryStatus.kt, client/src/main/kotlin/io/titandata/models/VolumeStatus.kt, server/src/endtoend-test/kotlin/io/titandata/EndToEndTest.kt, server/src/endtoend-test/kotlin/io/titandata/docker/DockerVolumeTest.kt, server/src/endtoend-test/kotlin/io/titandata/docker/LocalWorkflowTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesContextTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/apis/VolumesApi.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/context/docker/DockerZfsContext.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesCsiContext.kt, server/src/main/kotlin/io/titandata/orchestrator/RepositoryOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/VolumeOrchestrator.kt, server/src/test/kotlin/io/titandata/context/docker/DockerZfsContextTest.kt, server/src/test/kotlin/io/titandata/orchestrator/RepositoryOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/VolumeOrchestratorTest.kt
This adds implementations for k8s volume and commit status. As part of this work, I updated those APIs to report ready and error status out to clients, and separated out the volume status API from being embedded in repo status (should have been done when we created a first-class volume API).
`gradle build test integrationTest endtoendTest`. Ran kubernetes e2e tests on both DigitalOcean and EC2 clusters.
=> k8s status

server/src/integration-test/kotlin/io/titandata/CommitsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/orchestrator/NameUtil.kt, server/src/test/kotlin/io/titandata/orchestrator/NameUtilTest.kt
Now that I know how we're using names in kubernetes, this tightens our naming rules to better align with that environment. This way, users can't create a repository named "foo_bar" that cannot be used to name a k8s resource (creating a "foo_bar" pod would fail).
`gradle build test integrationTest endtoendTest`
=> update names to respect k8s limitations

client/src/main/kotlin/io/titandata/client/apis/ContextApi.kt, client/src/main/kotlin/io/titandata/models/Context.kt, server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/endtoend-test/kotlin/io/titandata/EndToEndTest.kt, server/src/endtoend-test/kotlin/io/titandata/docker/LocalWorkflowTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesConfigTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesContextTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesWorkflowTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/apis/ContextApi.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/context/docker/DockerZfsContext.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesCsiContext.kt, server/src/scripts/run
This adds the ability to specify a number of k8s parameters dynamically through the server environment. This is necessary to support things like having one titan context talking to an ec2 cluster and another talking to a digital ocean cluster. It also adds a context endpoint, which the CLI will use to ensure that it's connecting to the right cluster and using the right parameters (such as namespace) for its API calls. This is all groundwork for supporting first class configuration of contexts via the CLI.
`gradle build test integrationTest endtoendTest` including Kubernetes e2e tests.
=> k8s context configuration

client/src/main/kotlin/io/titandata/client/apis/OperationsApi.kt, server/src/endtoend-test/kotlin/io/titandata/EndToEndTest.kt, server/src/endtoend-test/kotlin/io/titandata/docker/LocalWorkflowTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/main/kotlin/io/titandata/apis/OperationsApi.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/metadata/MetadataProvider.kt, server/src/main/kotlin/io/titandata/metadata/OperationData.kt, server/src/main/kotlin/io/titandata/metadata/table/Operations.kt, server/src/main/kotlin/io/titandata/metadata/table/ProgressEntries.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/main/kotlin/io/titandata/orchestrator/Reaper.kt, server/src/test/kotlin/io/titandata/metadata/OperationMetadataTest.kt, server/src/test/kotlin/io/titandata/metadata/ProgressEntryMetadataTest.kt, server/src/test/kotlin/io/titandata/metadata/VolumeMetadataTest.kt, server/src/test/kotlin/io/titandata/operation/OperationExecutorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/ReaperTest.kt
Previously, operations existed only as long the last progress entry hadn't been read. The internal implementation had an in-memory map of operations that represented their current state. Both of these created challenges as we went to implement operations as an async pod for k8s. This PR changes the server such that operations always exist, whether they're in progress or not, and updates the APIs so that there is a global operations namespace instead of a per-repo one (which was always faked up). Running operations are now only meaningful for abort() (and waiting, but that's test-only). This will make it much easier to implement in k8s, as there won't have to be any tight interlock with the in-memory state. As part of this change, the responsibility for remembering the last progress entry …
=> refactor operations API

client/build.gradle.kts, server/build.gradle.kts, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/context/docker/DockerZfsContext.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesCsiContext.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/orchestrator/OperationOrchestrator.kt, server/src/test/kotlin/io/titandata/context/docker/DockerZfsContextTest.kt, server/src/test/kotlin/io/titandata/operation/OperationExecutorTest.kt, server/src/test/kotlin/io/titandata/orchestrator/OperationOrchestratorTest.kt
This change refactors the operation executor to separate out the data sync portion and push that into the context provider.  All the volumes are activated by the time that method is called, so the DockerZfs provider simply calls the sync volume method with the local path. In k8s, we'll launch a separate pod with PVCs for each of those volumes.
`gradle build test inegrationTest endtoendTest`, including Kubernetes tests.
=> refactor operations to isolate context-specific data sync

build.gradle.kts, server/build.gradle.kts, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesContextTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesTest.kt, server/src/endtoend-test/kotlin/io/titandata/kubernetes/KubernetesWorkflowTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesCsiContext.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesRunner.kt, server/src/main/kotlin/io/titandata/operation/OperationExecutor.kt, server/src/main/kotlin/io/titandata/orchestrator/NameUtil.kt, server/src/scripts/kubernetesOperation, server/src/test/kotlin/io/titandata/context/docker/DockerZfsContextTest.kt, server/src/test/kotlin/io/titandata/operation/OperationExecutorTest.kt
This adds push & pull ability for k8s repositories. To do this, we add an alternate entry point to the jarfile (and docker container) that is then invoked via a k8s job, along with a secret describing the operation and all the required volumes. This then invokes the remote operation and streams progress to stdout, which is picked up by the main titan-server process.
Some changes that stretched their tendrils into other code include renaming "_scratch" to "x-scratch", and the ability to specify the titan image name in the configuration (necessary for testing since titandata/titan won't be available in the k8s cluster)
`gradle build test integrationTest endtoendTest`, including new k8s tests. Ran with a modified titan CLI and successfully pushed to a S3 bucket and pulled down to a local …
=> k8s operations

server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/integration-test/kotlin/io/titandata/DockerVolumesApiTest.kt, server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt, server/src/integration-test/kotlin/io/titandata/RepositoriesApiTest.kt, server/src/main/kotlin/io/titandata/Application.kt, server/src/main/kotlin/io/titandata/apis/DockerVolumesApi.kt, server/src/main/kotlin/io/titandata/context/RuntimeContext.kt, server/src/main/kotlin/io/titandata/context/docker/DockerZfsContext.kt, server/src/main/kotlin/io/titandata/context/kubernetes/KubernetesCsiContext.kt, server/src/scripts-test/test-titan.sh, server/src/scripts-test/test-util.sh, server/src/scripts-test/test-zfs.sh, server/src/scripts/get-userland, server/src/scripts/kubernetesOperation, server/src/scripts/launch, server/src/scripts/run, server/src/scripts/teardown, server/src/scripts/titan.sh, server/src/scripts/util.sh, server/src/scripts/zfs.sh, server/src/test/kotlin/io/titandata/context/docker/DockerZfsContextTest.kt
This changes how we handle the instantiation of titan contexts, especially local docker contexts. Some of it just cleanup, unifying the variables. The most significant change is that we now listen on a docker plugin socket that is specific to the identity, rather than just "titan". This allows multiple local contexts to be run independently (not necessarily advisable, but important from an isolation perspective).
`gradle build test integrationTest endtoendTest`
=> support multiple local titan contexts

server/src/scripts/teardown
We were leaving a stale socket on teardown, we should remove it when the local context is uninstalled.
Ran teardown, ensured socket was removed.
=> remove plugin socket on teardown

client/build.gradle.kts, server/build.gradle.kts, server/src/endtoend-test/kotlin/io/titandata/DockerUtil.kt, server/src/endtoend-test/kotlin/io/titandata/remote/ssh/SshWorkflowTest.kt
This updates the SSH remote to 0.2.1, and adds a test for using the new unprivileged user in the SSH test server. These tests fail with the 0.2.0 remote but succeed with 0.2.1.
SSH endtoend tests.
=> support unprivileged users over SSH

server/src/scripts/teardown
With the addition of multiple contexts, it's no longer safe to assume that the context that was responsible for installing ZFS should be the one to uninstall it. Properly handling this, such as doing it only when the last context is torn down, will require some rethought. For now, I'm just updating it to not be an error so that we can drive on even if ZFS is in use.
=> don't fail if ZFS unload fails

client/src/main/kotlin/io/titandata/models/docker/PluginDescription.kt, openapi/titan.yaml, server/src/endtoend-test/kotlin/io/titandata/docker/DockerVolumeApi.kt, server/src/main/kotlin/io/titandata/apis/DockerVolumesApi.kt, server/src/main/kotlin/io/titandata/apis/OperationsApi.kt, server/src/main/kotlin/io/titandata/apis/VolumesApi.kt
We used to have an openapi definition for titan-server, but moved away from it because (a) we were doing weird things with inheritance and the docker volume api and (b) the kotlin client generation was pretty sub-par. Now that we've addressed (a), and are looking at moving to golang, it would be nicer if we could go back to a standard openapi definition with generated clients.
This adds an openapi definition file, and makes a few adjustments to HTTP codes / etc that I noticed while implementing it. It has been validated with the openapi validator, but there's no way to know it truly works until we start using it.
Tested with swagger editor, viewed resulting docs, manually reviewed against server API implementation.
=> add openapi definition

server/src/integration-test/kotlin/io/titandata/OperationsApiTest.kt
Fixes #101 
While doing some OpenAPI documentation, I fixed the status codes for push/pull as they actually create operations (and hence should be 201). But I forgot to run the integration tests.
Ran integration tests.
=> fix tests for new HTTP status codes

openapi/titan.yml
While working on the go client, I noticed that the generator didn't like a schema named "error", as that is a reserved word. Rather than using the default "model_error", we should update our spec to change it to "apiError" instead. For consistency, I also made the "badinput" and "nosuchobject" responses camel case (though this has no real effect since they reference the same apiError schema).
Generated go client. Verified no warnings, and checked generated files for use of ApiError.
=> update openapi to better work with go

server/src/integration-test/kotlin/io/titandata/VolumesApiTest.kt, server/src/main/kotlin/io/titandata/orchestrator/VolumeOrchestrator.kt
Currently, if you attempt to list volumes of a non-existent repo, you get a null pointer exception. Other volume methods will do a `getRepository()`call  to make sure the repository exists and we get a nice exception (and therefore 404 error) if it doesn't.
Added new integration tests that failed on the old code and now works on the new. re-ran all tests. I did not attempt to build out a complete volumes API integration test suite as a result of this change.
=> list volumes of non-existent repo should return 404

openapi/titan.yml
There was a typo of "propertiers" that was breaking titan-client-go.
Regenerated client and made sure `omitempty` was not present.
=> fix properties typo in openapi spec

openapi/titan.yml
This mirrors a corresponding fix in the `titan-go-client` `titan.yml`, where we were incorrectly declaring `getCommitStatus()` as POST, not GET.
=> getCommitStatus should be GET

openapi/titan.yml
Mirror of `titan-client-go` changes.
=> remote parameters are not optional for push/pull

server/build.gradle.kts, server/docker/server.Dockerfile, server/gradle/docker.gradle.kts, server/src/scripts/get-userland, server/src/scripts/kubernetesOperation, server/src/scripts/launch, server/src/scripts/run, server/src/scripts/teardown, server/src/scripts/titan.sh, server/src/scripts/util.sh, server/src/scripts/zfs.sh
ZFS build version updated to 2.1.5 while the min zfs version remains at 2.0.0. E2E testing indicates compatibility because no other code needed to be updated between any 2.0 releases and 2.1.5. 
The underlying docker image for titan server has been update to be ubuntu:focal (20.04). This is the same version used by the nightly zfs-releases job to keep github actions runner up to date. There are some issues when compiling with ubuntu:22.04 because it ships with a newer version of openssl, so staying on ubuntu:20.04 for now as it also runs on 22.04.
=> big update to zfs 2.1.5 and ubuntu:focal
